### ISSUE TITLE
test_issue

### ISSUE THREAD

**Issue by cdnetwork** [cdnetworks-jaeger/proxygen#1]
This is a test issue for http temporary response.

**Comment by gilgil1973** [comment]
https://github.com/cdnetworks-jaeger/proxygen/tree/test_issue

**Comment by gilgil1973** [comment]
Fix compile error(HTTPConnector.cpp and HTTPSession.cpp).
Modify temporary HTTP response "hello world"(EchoHandler.cpp).

Done in
https://github.com/cdnetworks-jaeger/proxygen/commit/b1876d1e68b8f77e790a32ad154b03166db664b7
